---
- hosts: all
  vars:
    ansible_bender:
      base_image: "registry.fedoraproject.org/fedora-toolbox:36"
      buildah_from_extra_args: "--dns 8.8.8.8"
      ansible_extra_args: "-vvv"
      cache_tasks: true
      layering: false
      squash: true

      working_container:
        volumes:
          - "{{ playbook_dir }}:/src"

      target_image:
        name: toolbox
        user: "1000"
        labels:
          com.trimbletl.image.source: "https://github.com/aairey/toolbox-aairey"
          com.trimbletl.image.vendor: "aairey"
          com.trimbletl.image.created: "20220610"
          com.trimbletl.image.version: "0.2"
          com.trimbletl.image.revision: "main"
    fedora_edition: 'toolbox'
  pre_tasks:
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
      tags: debug_info
  roles:
    - name: aairey.os_base
    #- name: aairey.dotfiles # dotfiles to be stored in homedir, not in container image
  tasks:
    - name: Clean up dnf caches
      command: dnf clean all
      become: yes